[tool.poetry]
name = "ridewithgps-to-cuesheet"
version = "0.3.0"
description = "Convert RideWithGPS maps to BC Randonneurs cuesheets"
authors = ["Etienne H <et@hossack.me>"]
license = "GPLv2"

[tool.poetry.dependencies]
python = "^3.9"
XlsxWriter = "^3.0.1"
requests = "^2.28.2"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.263"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = [
    "C9",
    # "D", -- aspirational
    "E",
    "F",
    "I",
    "W",
]
exclude = [".git", "__pycache__", ".mypy_stubs", ".venv"]
ignore = ["D100", "D101", "D102", "D103", "D104", "D106", "D203"]
line-length = 120

[tool.ruff.isort]
split-on-trailing-comma = false

[tool.ruff.mccabe]
max-complexity = 10
