[tool.poetry]
name = "ridewithgps-to-cuesheet"
version = "0.2.0"
description = ""
authors = ["Etienne H <et@hossack.me>"]
license = "GPLv2"

[tool.poetry.dependencies]
python = "^3.9"
XlsxWriter = "^3.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
