from . import xmlwriter as xmlwriter
from _typeshed import Incomplete

class Format(xmlwriter.XMLwriter):
    xf_format_indices: Incomplete
    dxf_format_indices: Incomplete
    xf_index: Incomplete
    dxf_index: Incomplete
    num_format: str
    num_format_index: int
    font_index: int
    has_font: bool
    has_dxf_font: bool
    bold: int
    underline: int
    italic: int
    font_name: str
    font_size: int
    font_color: int
    font_strikeout: int
    font_outline: int
    font_shadow: int
    font_script: int
    font_family: int
    font_charset: int
    font_scheme: str
    font_condense: int
    font_extend: int
    theme: int
    hyperlink: bool
    xf_id: int
    hidden: int
    locked: int
    text_h_align: int
    text_wrap: int
    text_v_align: int
    text_justlast: int
    rotation: int
    fg_color: int
    bg_color: int
    pattern: int
    has_fill: bool
    has_dxf_fill: bool
    fill_index: int
    fill_count: int
    border_index: int
    has_border: bool
    has_dxf_border: bool
    border_count: int
    bottom: int
    bottom_color: int
    diag_border: int
    diag_color: int
    diag_type: int
    left: int
    left_color: int
    right: int
    right_color: int
    top: int
    top_color: int
    indent: int
    shrink: int
    merge_range: int
    reading_order: int
    just_distrib: int
    color_indexed: int
    font_only: int
    quote_prefix: bool
    checkbox: bool
    def __init__(self, properties: Incomplete | None = None, xf_indices: Incomplete | None = None, dxf_indices: Incomplete | None = None) -> None: ...
    def set_font_name(self, font_name) -> None: ...
    def set_font_size(self, font_size: int = 11) -> None: ...
    def set_font_color(self, font_color) -> None: ...
    def set_bold(self, bold: bool = True) -> None: ...
    def set_italic(self, italic: bool = True) -> None: ...
    def set_underline(self, underline: int = 1) -> None: ...
    def set_font_strikeout(self, font_strikeout: bool = True) -> None: ...
    def set_font_script(self, font_script: int = 1) -> None: ...
    def set_font_outline(self, font_outline: bool = True) -> None: ...
    def set_font_shadow(self, font_shadow: bool = True) -> None: ...
    def set_num_format(self, num_format) -> None: ...
    def set_locked(self, locked: bool = True) -> None: ...
    def set_hidden(self, hidden: bool = True) -> None: ...
    def set_align(self, alignment) -> None: ...
    def set_center_across(self, align_type: Incomplete | None = None) -> None: ...
    def set_text_wrap(self, text_wrap: bool = True) -> None: ...
    def set_rotation(self, rotation) -> None: ...
    def set_indent(self, indent: int = 1) -> None: ...
    def set_shrink(self, shrink: bool = True) -> None: ...
    def set_text_justlast(self, text_justlast: bool = True) -> None: ...
    def set_pattern(self, pattern: int = 1) -> None: ...
    def set_bg_color(self, bg_color) -> None: ...
    def set_fg_color(self, fg_color) -> None: ...
    def set_border(self, style: int = 1) -> None: ...
    def set_border_color(self, color) -> None: ...
    def set_bottom(self, bottom: int = 1) -> None: ...
    def set_bottom_color(self, bottom_color) -> None: ...
    def set_diag_type(self, diag_type: int = 1) -> None: ...
    def set_left(self, left: int = 1) -> None: ...
    def set_left_color(self, left_color) -> None: ...
    def set_right(self, right: int = 1) -> None: ...
    def set_right_color(self, right_color) -> None: ...
    def set_top(self, top: int = 1) -> None: ...
    def set_top_color(self, top_color) -> None: ...
    def set_diag_color(self, diag_color) -> None: ...
    def set_diag_border(self, diag_border: int = 1) -> None: ...
    def set_quote_prefix(self, quote_prefix: bool = True) -> None: ...
    def set_checkbox(self, checkbox: bool = True) -> None: ...
    def set_has_font(self, has_font: bool = True) -> None: ...
    def set_has_fill(self, has_fill: bool = True) -> None: ...
    def set_font_index(self, font_index) -> None: ...
    def set_xf_index(self, xf_index) -> None: ...
    def set_dxf_index(self, dxf_index) -> None: ...
    def set_num_format_index(self, num_format_index) -> None: ...
    def set_text_h_align(self, text_h_align) -> None: ...
    def set_text_v_align(self, text_v_align) -> None: ...
    def set_reading_order(self, direction: int = 0) -> None: ...
    def set_valign(self, align) -> None: ...
    def set_font_family(self, font_family) -> None: ...
    def set_font_charset(self, font_charset) -> None: ...
    def set_font_scheme(self, font_scheme) -> None: ...
    def set_font_condense(self, font_condense) -> None: ...
    def set_font_extend(self, font_extend) -> None: ...
    def set_theme(self, theme) -> None: ...
    def set_hyperlink(self, hyperlink: bool = True) -> None: ...
    def set_color_indexed(self, color_index) -> None: ...
    def set_font_only(self, font_only: bool = True) -> None: ...
    def set_font(self, font_name) -> None: ...
    def set_size(self, font_size) -> None: ...
    def set_color(self, font_color) -> None: ...
