from .exceptions import UndefinedImageSize as UndefinedImageSize, UnsupportedImageFormat as UnsupportedImageFormat
from _typeshed import Incomplete
from io import BytesIO
from xlsxwriter.url import Url as Url

DEFAULT_DPI: float

class Image:
    filename: Incomplete
    image_data: Incomplete
    image_name: Incomplete
    def __init__(self, source: str | BytesIO) -> None: ...
    @property
    def image_type(self) -> str: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    @property
    def x_dpi(self) -> float: ...
    @property
    def y_dpi(self) -> float: ...
    @property
    def description(self) -> str | None: ...
    @description.setter
    def description(self, value: str): ...
    @property
    def decorative(self) -> bool: ...
    @decorative.setter
    def decorative(self, value: bool): ...
    @property
    def url(self) -> Url | None: ...
    @url.setter
    def url(self, value: Url): ...
