from _typeshed import Incomplete

COL_NAMES: dict[int, str]
CHAR_WIDTHS: Incomplete
EMOJIS: str
RE_LEADING_WHITESPACE: Incomplete
RE_TRAILING_WHITESPACE: Incomplete
RE_RANGE_PARTS: Incomplete
RE_QUOTE_RULE1: Incomplete
RE_QUOTE_RULE2: Incomplete
RE_QUOTE_RULE3: Incomplete
RE_QUOTE_RULE4_ROW: Incomplete
RE_QUOTE_RULE4_COLUMN: Incomplete

def xl_rowcol_to_cell(row: int, col: int, row_abs: bool = False, col_abs: bool = False) -> str: ...
def xl_rowcol_to_cell_fast(row: int, col: int) -> str: ...
def xl_col_to_name(col: int, col_abs: bool = False) -> str: ...
def xl_cell_to_rowcol(cell_str: str) -> tuple[int, int]: ...
def xl_cell_to_rowcol_abs(cell_str: str) -> tuple[int, int, bool, bool]: ...
def xl_range(first_row: int, first_col: int, last_row: int, last_col: int) -> str: ...
def xl_range_abs(first_row: int, first_col: int, last_row: int, last_col: int) -> str: ...
def xl_range_formula(sheetname: str, first_row: int, first_col: int, last_row: int, last_col: int) -> str: ...
def quote_sheetname(sheetname: str) -> str: ...
def cell_autofit_width(string: str) -> int: ...
def xl_pixel_width(string: str) -> int: ...
